application_sonata_super_market:
    resource: "@ApplicationSonataSuperMarketBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
shtumi_useful:
    resource: '@ShtumiUsefulBundle/Resources/config/routing.xml'