sonata_admin:
  title: SUPER MARKET
  templates:
    edit: ApplicationSonataSuperMarketBundle::edit.html.twig
  dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Super Market Admin</h2> <p>It is a super market admin page</p>"} }  
