Application\Sonata\SuperMarketBundle\Entity\OrderItem:
    type: entity
    table: supermarket_orderitem
    repositoryClass: Application\Sonata\SuperMarketBundle\Entity\OrderItemRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: integer
        total:
            type: float
        price:
            type: float
    manyToOne:
     purchaseorder:
         targetEntity: PurchaseOrder
         inversedBy: orderitem
         joinColumn:
           name: purchase_id
           referencedColumnName: id
     products:
        targetEntity: Product
        inversedBy: orderitem
        joinColumn:
          name: product_order_id
          referencedColumnName: id
    lifecycleCallbacks: {  }
